name: Push-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: 3.111.42.77
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu

            # If project folder doesn’t exist, clone it
            rm -rf cicd
            if [ ! -d "cicd" ]; then
              git clone -b main https://github.com/kaushal-kumar-it/cicd.git
            fi

            cd cicd
            git pull origin main

            npm install
            npm run build
            pm2 restart app || pm2 start npm --name "app" -- start



