name: Push-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Execute remote SSH commands using private key
        uses: appleboy/ssh-action@v1
        with:
          host: 3.111.42.77
          username: ubuntu
          key: ${{secrets.EC2_SSH_KEY }} # <-- Private key stored in GitHub secrets
          port: 22
          script: whoami
