name: Push-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 3.111.42.77
          username: ubuntu
          password: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: whoami
      